#!/usr/bin/env bash
source ~/.profile
source ~/.bashrc
source /ptv/add_to_bash
source /ptv/add_to_aliases
source /ptv/add_to_path
source /ptv/healer/bbplats/bc/.venv/bin/activate
seplog >> /ptv/healer/bbplats/bc/logs/bcjob.log
# echo date,time,venv and current working directory
echo "[+] Current date and time: $(TZ=":Asia/Tehran" date)" >> /ptv/healer/bbplats/bc/logs/bcjob.log
echo "[+] Current PATH: $PATH" >> /ptv/healer/bbplats/bc/logs/bcjob.log
echo "[+] Current virtual environment: $(which python3)" >> /ptv/healer/bbplats/bc/logs/bcjob.log
echo "[+] Current working directory: $(pwd)" >> /ptv/healer/bbplats/bc/logs/bcjob.log
# Check whether notifioo_sender is available
a=$(which notifio_sender)
# If a is empty, then notifio_sender is not available
if [ -z "$a" ]; then
    echo "notifio_sender is not available. Please install it first."
    exit 1
fi
# Send a started job notification to discord.debug channel
notifio_sender --title 'BugCrowd Job Started' --discord.debug " Started Job For bc - Fetching all programs and reporting minor and major changes" >> /ptv/healer/bbplats/bc/logs/bcjob.log
# Run the scripts
python3 /ptv/healer/bbplats/bc/get_programs.py >> /ptv/healer/bbplats/bc/logs/bcjob.log
python3 /ptv/healer/bbplats/bc/get_program.py >> /ptv/healer/bbplats/bc/logs/bcjob.log
python3 /ptv/healer/bbplats/bc/diff_program.py >> /ptv/healer/bbplats/bc/logs/bcjob.log
# Send a finished job notification to logs file
echo "Job finished" >> /ptv/healer/bbplats/bc/logs/bcjob.log
echo "" >> /ptv/healer/bbplats/bc/logs/bcjob.log
echo "" >> /ptv/healer/bbplats/bc/logs/bcjob.log