#!/usr/bin/env bash
# Get current script working directory
binpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
seplog="▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃"
# Create folder $binpath/logs/ if does not exist
mkdir -p "$binpath/logs"
echo $seplog >> $binpath/logs/bcjob.log
echo "Job started" >> $binpath/logs/bcjob.log
source /root/.bashrc
# source /ptv/add_to_path.sh
# source /ptv/setup-everything/.bin/setup-bashrc-bin-path.sh

srclist=()
# define an empty array
declare -a srclist
# iterate over lines of bashrc_content and echo them
while IFS= read -r line; do
    # If line starts with 'source', then add it to srclist
    if [[ $line == source* ]]; then
        # select everything after 'source '
        srclist+=("${line:7}")
    fi
done < ~/.bashrc
for i in "${srclist[@]}"
do
    source "$i" > /dev/null 2>&1
done

# echo date,time,venv and current working directory
echo "[+] Current date and time: $(TZ=":Asia/Tehran" date)" >> $binpath/logs/bcjob.log
echo "[+] Current PATH: $PATH" >> $binpath/logs/bcjob.log
echo "[+] Current virtual environment: $(which python3)" >> $binpath/logs/bcjob.log
echo "[+] Current working directory: $(pwd)" >> $binpath/logs/bcjob.log
# Check whether notifio is available
a=$(which notifio)
# If a is empty, then notifio is not available
if [ -z "$a" ]; then
    echo "notifio is not available. Please install it first." >> $binpath/logs/bcjob.log
    exit 1
fi
# Send a started job notification to discord.debug channel
notifio --title 'BugCrowd Job Started' --discord -ch debug -m "Started Job For bc - Fetching all programs and reporting minor and major changes" >> $binpath/logs/bcjob.log
# Run the scripts
$binpath/.bin/get_programs_bc.py >> $binpath/logs/bcjob.log
$binpath/.bin/get_program_bc.py >> $binpath/logs/bcjob.log
$binpath/.bin/diff_program_bc.py >> $binpath/logs/bcjob.log
# Send a finished job notification to logs file
echo "Job finished" >> $binpath/logs/bcjob.log
echo "" >> $binpath/logs/bcjob.log
echo "" >> $binpath/logs/bcjob.log
