#!/usr/bin/env bash
source ~/.profile
source ~/.bashrc
source /ptv/add_to_bashrc.sh
source /ptv/add_to_aliases.sh
source /ptv/add_to_path.sh
# Create folder /ptv/healer/bbplats/h1/logs/ if does not exist
mkdir -p /ptv/healer/bbplats/h1/logs/
seplog >> /ptv/healer/bbplats/h1/logs/h1job.log
# echo date,time,venv and current working directory
echo "[+] Current date and time: $(TZ=":Asia/Tehran" date)" >> /ptv/healer/bbplats/h1/logs/h1job.log
echo "[+] Current PATH: $PATH" >> /ptv/healer/bbplats/h1/logs/h1job.log
echo "[+] Current virtual environment: $(which python3)" >> /ptv/healer/bbplats/h1/logs/h1job.log
echo "[+] Current working directory: $(pwd)" >> /ptv/healer/bbplats/h1/logs/h1job.log
# Check whether notifioo_sender is available
a=$(which notifio_sender)
# If a is empty, then notifio_sender is not available
if [ -z "$a" ]; then
    echo "notifio_sender is not available. Please install it first."
    exit 1
fi
# Send a started job notification to discord.debug channel
notifio_sender --title 'HackerOne Job Started' --discord.debug "Started Job For H1 - Fetching all programs and reporting minor and major changes" >> /ptv/healer/bbplats/h1/logs/h1job.log
# Run the scripts
/ptv/healer/bbplats/h1/get_programs.py >> /ptv/healer/bbplats/h1/logs/h1job.log
/ptv/healer/bbplats/h1/get_program.py >> /ptv/healer/bbplats/h1/logs/h1job.log
/ptv/healer/bbplats/h1/diff_program.py >> /ptv/healer/bbplats/h1/logs/h1job.log
# Send a finished job notification to logs file
echo "Job finished" >> /ptv/healer/bbplats/h1/logs/h1job.log
echo "" >> /ptv/healer/bbplats/h1/logs/h1job.log
echo "" >> /ptv/healer/bbplats/h1/logs/h1job.log