#!/usr/bin/env bash
# Get current script working directory
binpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
seplog="▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃"
# Create folder $binpath/logs/ if does not exist
mkdir -p "$binpath/logs"
echo $seplog >> $binpath/logs/h1job.log
echo "Job started" >> $binpath/logs/h1job.log
source /root/.bashrc
# source /ptv/add_to_path.sh
# source /ptv/setup-everything/.bin/setup-bashrc-bin-path.sh

srclist=()
# define an empty array
declare -a srclist
# iterate over lines of bashrc_content and echo them
while IFS= read -r line; do
    # If line starts with 'source', then add it to srclist
    if [[ $line == source* ]]; then
        # select everything after 'source '
        # echo "${line:7}" >> $binpath/logs/h1job.log
        srclist+=("${line:7}")
    fi
done < ~/.bashrc

# echo all members of srclist at once
# echo "${srclist[@]}" >> $binpath/logs/h1job.log

for i in "${srclist[@]}"
do
    # echo len of srclist
    # echo "${#srclist[@]}" >> $binpath/logs/h1job.log
    # echo "$i" >> $binpath/logs/h1job.log
    source "$i" > /dev/null 2>&1
    # echo "pass" >> $binpath/logs/h1job.log
done

# echo date,time,venv and current working directory
echo "[+] Current date and time: $(TZ=":Asia/Tehran" date)" >> $binpath/logs/h1job.log
echo "[+] Current PATH: $PATH" >> $binpath/logs/h1job.log
echo "[+] Current virtual environment: $(which python3)" >> $binpath/logs/h1job.log
echo "[+] Current working directory: $(pwd)" >> $binpath/logs/h1job.log
# Check whether notifioo_sender is available
a=$(which notifio_sender)
# If a is empty, then notifio_sender is not available
if [ -z "$a" ]; then
    echo "notifio_sender is not available. Please install it first." >> $binpath/logs/h1job.log
    exit 1
fi
# Send a started job notification to discord.debug channel
notifio --title 'HackerOne Job Started' --discord -ch debug -m "Started Job For H1 - Fetching all programs and reporting minor and major changes" >> $binpath/logs/h1job.log
# Run the scripts
$binpath/.bin/get_programs_h1.py >> $binpath/logs/h1job.log
$binpath/.bin/get_program_h1.py >> $binpath/logs/h1job.log
$binpath/.bin/diff_program_h1.py >> $binpath/logs/h1job.log
# Send a finished job notification to logs file
echo "Job finished" >> $binpath/logs/h1job.log
echo "" >> $binpath/logs/h1job.log
echo "" >> $binpath/logs/h1job.log
